# -----------------------------------------------------------------------------
# User configuration
[ -f "$HOME/.config-work.sh" ] && . "$HOME/.config-work.sh"
[ -f "$HOME/.config-common.sh" ] && . "$HOME/.config-common.sh"
