# -----------------------------------------------------------------------------
# User configuration
[ -f "$HOME/.config-work.sh" ] && . "$HOME/.config-work.sh"
[ -f "$HOME/.config-common.sh" ] && . "$HOME/.config-common.sh"

# Better look and feel.
export QT_QPA_PLATFORMTHEME="qt5ct"

if [ "$(tty)" = "/dev/tty1" ]; then
   [ -x "$(command -v sway)" ] && exec sway
fi
