#!/usr/bin/env zsh

if [[ ! -x "$(command -v nixos-version)" ]] then
    export ZSH="$HOME/.oh-my-zsh"
    ZSH_THEME="intheloop"
    plugins=(git kubectl history gcloud mix npm yarn rust rsync postgres fzf docker-compose zsh-autosuggestions zsh-syntax-highlighting)
    source $ZSH/oh-my-zsh.sh
fi

# ------------------------------------------------------------------------------
s="$HOME/.shell-aliases"; [ -d "$s" ] && for f in "$s"/*.sh; do . $f; done
s="$HOME/.appearance.sh"; [ -f "$s" ] && . "$s"
s="$HOME/.config-common.sh"; [ -f "$s" ] && . "$s"
s="$HOME/.fzf-projects.zsh"; [ -f "$s" ] && . "$s"
s="$HOME/.fzf-notes.zsh"; [ -f "$s" ] && . "$s"
s="$HOME/.bemenu-commander.zsh"; [ -f "$s" ] && . "$s"

unset s
